# Generated by Django 5.2.8 on 2025-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
