# Generated by Django 5.2.8 on 2025-11-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_ticket_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_confirmed',
        ),
    ]
