# Generated by Django 5.2.8 on 2025-11-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_remove_ticket_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_no', models.CharField(max_length=20)),
                ('max_speed', models.IntegerField(help_text='in km/h')),
                ('has_food_service', models.BooleanField(default=False)),
                ('has_reclining_seats', models.BooleanField(default=False)),
                ('has_disability_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trains.train'),
        ),
    ]
