# Generated by Django 5.2.8 on 2025-11-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_train_trip_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First Class')], default='Economy', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip_type',
            field=models.CharField(choices=[('One-Way', 'One-Way'), ('Round-Trip', 'Round-Trip')], default='One-Way', max_length=20),
        ),
        migrations.AddField(
            model_name='train',
            name='has_folding_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='has_luggage_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='has_vending_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='no_of_seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='train',
            name='no_of_toilets',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='train',
            name='max_speed',
            field=models.IntegerField(help_text='km/h'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trains.train'),
        ),
        migrations.CreateModel(
            name='MaintenanceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_no', models.CharField(max_length=20, unique=True)),
                ('date_completed', models.DateField()),
                ('crew_in_charge', models.CharField(max_length=100)),
                ('task_completed', models.TextField()),
                ('condition', models.CharField(max_length=50)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='trains.train')),
            ],
        ),
    ]
