# Generated by Django 5.2.8 on 2025-11-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0006_ticket_seat_class_ticket_trip_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('Local', 'Local System'), ('Inter-town', 'Inter-town System')], max_length=20)),
                ('is_one_way', models.BooleanField(help_text='True = Local, False = Inter-town')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='train_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='trains.trainsystem'),
        ),
    ]
